/* Step-by-step guide for every exercise, written for someone who has never done it.
   s = set up, m = the movement in order, f = where you should feel it, e = how to make it easier.
   DRAFT: for review by a qualified exercise professional. */
const GUIDES = {
  /* squat */
  'Sit to stand': { s: 'Sit on the front half of a sturdy chair, feet flat and hip-width apart.', m: ['Cross your arms over your chest and lean forward a little.', 'Push through your feet and stand all the way up.', 'Lower yourself back down slowly, counting to three.'], f: 'Thighs and bottom', e: 'Use a higher seat, or push lightly on your thighs with your hands.' },
  'Sit to stand, high seat': { s: 'Add a firm cushion to a sturdy chair, or use a higher seat. Feet flat, hip-width apart.', m: ['Lean forward a little, nose over your toes.', 'Push through your whole foot and stand up.', 'Sit back down slowly and under control.'], f: 'Thighs and bottom, not the knees', e: 'Raise the seat further, or use your hands on the chair arms.' },
  'Goblet squat': { s: 'Stand with feet a little wider than your hips. Hold one dumbbell upright against your chest.', m: ['Sit your hips back and down as if to a chair behind you.', 'Go as low as feels comfortable, chest up.', 'Push the floor away and stand tall.'], f: 'Thighs and bottom', e: 'Squat down to touch a chair, or do it without the weight.' },
  'Kettlebell goblet squat': { s: 'Stand with feet a little wider than your hips. Hold the kettlebell by its handle sides against your chest.', m: ['Sit your hips back and down as if to a chair behind you.', 'Go as low as feels comfortable, chest up.', 'Push the floor away and stand tall.'], f: 'Thighs and bottom', e: 'Squat down to touch a chair, or do it without the bell.' },
  'Band squat': { s: 'Stand on the middle of the band, feet hip-width. Hold the ends at your shoulders.', m: ['Sit your hips back and down.', 'Go as low as feels comfortable.', 'Stand up against the pull of the band.'], f: 'Thighs and bottom', e: 'Hold the band lower, at your hips, or drop the band.' },
  'Leg press': { s: 'Sit back in the seat with your whole back supported. Feet flat on the plate, hip-width apart.', m: ['Release the safety handles.', 'Bend your knees slowly until they reach a right angle.', 'Press the plate away without locking your knees straight.'], f: 'Thighs and bottom', e: 'Take weight off, or bend your knees less.' },

  /* push */
  'Incline press-up': { s: 'Place your hands on a kitchen worktop, a little wider than your shoulders. Walk your feet back until your body is a straight line.', m: ['Bend your elbows and lower your chest towards the worktop.', 'Keep your body straight, no sagging hips.', 'Press yourself back up.'], f: 'Chest, shoulders and the backs of your arms', e: 'Stand closer, or use a wall instead of a worktop.' },
  'Wall press-up': { s: 'Stand an arm\'s length from a wall. Hands flat on it at chest height.', m: ['Bend your elbows and lean your chest towards the wall.', 'Keep your heels down and body straight.', 'Press yourself back to standing.'], f: 'Chest, shoulders and the backs of your arms', e: 'Stand closer to the wall.' },
  'Floor press': { s: 'Lie on your back, knees bent, feet flat. Hold a dumbbell in each hand above your chest.', m: ['Lower the weights until your elbows touch the floor softly.', 'Pause for a moment.', 'Press them back up above your chest.'], f: 'Chest and the backs of your arms', e: 'Use lighter weights, or one arm at a time.' },
  'Kettlebell floor press': { s: 'Lie on your back, knees bent. Hold the kettlebell in one hand, the bell resting on the back of your forearm.', m: ['Lower until your elbow touches the floor softly.', 'Keep your wrist straight.', 'Press back up. Do all your reps, then swap arms.'], f: 'Chest and the back of your arm', e: 'Use a lighter bell, or hold it with both hands.' },
  'Dumbbell bench press': { s: 'Lie back on the bench, feet flat on the floor. Hold a dumbbell in each hand above your chest.', m: ['Lower the weights to chest height, elbows a little out from your sides.', 'Pause for a moment.', 'Press them back up.'], f: 'Chest and the backs of your arms', e: 'Use lighter weights, or do it lying on the floor.' },
  'Band chest press': { s: 'Loop the band round something solid behind you at chest height. Face away, one end in each hand, one foot forward.', m: ['Start with your hands by your chest.', 'Press both hands straight forward.', 'Bring them back slowly.'], f: 'Chest and the backs of your arms', e: 'Step back towards the anchor so the band is slacker.' },
  'Chest press machine': { s: 'Adjust the seat so the handles are level with the middle of your chest. Back flat against the pad.', m: ['Grip the handles.', 'Press forward until your arms are nearly straight.', 'Return slowly, without letting the weights clatter.'], f: 'Chest and the backs of your arms', e: 'Take weight off.' },

  /* pull */
  'Loaded bag row': { s: 'Fill a strong bag with tins or books. Put one hand on a chair seat, feet apart, back flat like a table.', m: ['Hold the bag in your free hand, arm hanging straight.', 'Pull it up to your hip, elbow brushing your ribs.', 'Lower it slowly. Do all your reps, then swap sides.'], f: 'Upper back and the back of your shoulder', e: 'Take things out of the bag, or stand more upright.' },
  'One-arm row': { s: 'Put one hand on a chair seat, feet apart, back flat like a table. Dumbbell in the other hand.', m: ['Let the weight hang straight down.', 'Pull it up to your hip, elbow brushing your ribs.', 'Lower it slowly. Do all your reps, then swap sides.'], f: 'Upper back and the back of your shoulder', e: 'Use a lighter weight, or stand more upright.' },
  'Kettlebell row': { s: 'Put one hand on a chair seat, feet apart, back flat like a table. Kettlebell in the other hand.', m: ['Let the bell hang straight down.', 'Pull it up to your hip, elbow brushing your ribs.', 'Lower it slowly. Do all your reps, then swap sides.'], f: 'Upper back and the back of your shoulder', e: 'Use a lighter bell, or stand more upright.' },
  'Band row': { s: 'Loop the band round something solid at waist height. Sit or stand facing it, an end in each hand, arms straight.', m: ['Sit or stand tall.', 'Pull your elbows back past your ribs and squeeze your shoulder blades together.', 'Let your arms straighten slowly.'], f: 'Between your shoulder blades', e: 'Move closer to the anchor.' },
  'Seated row machine': { s: 'Sit with your chest against the pad, feet on the rests. Reach forward for the handles.', m: ['Sit tall.', 'Pull the handles back until your elbows pass your ribs.', 'Return slowly.'], f: 'Between your shoulder blades', e: 'Take weight off.' },

  /* core */
  'Dead bug': { s: 'Lie on your back. Arms straight up to the ceiling, knees bent above your hips.', m: ['Press your lower back gently into the floor.', 'Slowly lower one arm behind you and straighten the opposite leg.', 'Bring them back and swap sides. Keep going for the time.'], f: 'Deep in your tummy', e: 'Move only your legs, or only tap your heel to the floor.' },
  'Pallof press': { s: 'Loop the band round something solid at chest height. Stand side-on to it, both hands holding the band at your chest.', m: ['Step away until the band is taut.', 'Press your hands straight out in front of you.', 'Hold. Do not let the band twist you. Swap sides halfway.'], f: 'The sides of your waist', e: 'Stand closer to the anchor.' },
  'Seated knee lift': { s: 'Sit tall on the front of a sturdy chair. Hold the sides of the seat.', m: ['Brace your tummy as if about to cough.', 'Lift one knee a few inches and hold it.', 'Lower slowly and swap legs. Keep going for the time.'], f: 'Low in your tummy and the front of your hip', e: 'Lift your knee less high, or just lift your heel.' },

  /* hinge */
  'Glute bridge': { s: 'Lie on your back, knees bent, feet flat and hip-width apart, arms by your sides.', m: ['Squeeze your bottom.', 'Lift your hips until your body is a straight line from knees to shoulders.', 'Pause for two seconds, then lower slowly.'], f: 'Bottom and the backs of your thighs', e: 'Lift your hips less high.' },
  'Chair hip hinge': { s: 'Stand behind a sturdy chair, hands resting on its back, feet hip-width apart.', m: ['Soften your knees.', 'Push your hips straight back as if closing a drawer with your bottom. Back stays long.', 'Squeeze your bottom and stand tall.'], f: 'Bottom and the backs of your thighs', e: 'Push your hips back a shorter distance.' },
  'Romanian deadlift': { s: 'Stand tall, feet hip-width, a dumbbell in each hand in front of your thighs.', m: ['Soften your knees.', 'Push your hips back and slide the weights down your thighs to your knees. Back stays long.', 'Squeeze your bottom and stand tall.'], f: 'Backs of your thighs and bottom, not your lower back', e: 'Use lighter weights and stop higher up your thighs.' },
  'Dumbbell Romanian deadlift': { s: 'Stand tall, feet hip-width, a dumbbell in each hand in front of your thighs.', m: ['Soften your knees.', 'Push your hips back and slide the weights down your thighs to your knees. Back stays long.', 'Squeeze your bottom and stand tall.'], f: 'Backs of your thighs and bottom, not your lower back', e: 'Use lighter weights and stop higher up your thighs.' },
  'Kettlebell deadlift': { s: 'Stand with the kettlebell on the floor between your feet, feet a little wider than your hips.', m: ['Push your hips back and bend your knees to grip the handle. Back stays long.', 'Push the floor away and stand up tall.', 'Lower it back to the floor the same way.'], f: 'Bottom and thighs', e: 'Raise the bell on a step or thick book so you bend less.' },
  'Band deadlift': { s: 'Stand on the middle of the band, feet hip-width. Hold an end in each hand.', m: ['Push your hips back and let your hands slide down to your knees. Back stays long.', 'Squeeze your bottom and stand tall against the band.', 'Lower slowly.'], f: 'Bottom and the backs of your thighs', e: 'Hold the band higher so it is slacker.' },

  /* lunge */
  'Step-up': { s: 'Stand facing the bottom stair. Hold the banister.', m: ['Place your whole foot on the step.', 'Push through that foot and stand up onto the step.', 'Step back down slowly. Do all your reps, then swap legs.'], f: 'Thigh and bottom of the stepping leg', e: 'Use a lower step, and use the banister more.' },
  'Supported step-back': { s: 'Stand side-on to a sturdy chair or worktop, one hand holding it.', m: ['Step one foot back about a stride.', 'Bend both knees a little, as far as feels steady.', 'Push through your front foot and step back together. Swap legs halfway.'], f: 'Thigh and bottom of the front leg', e: 'Take a shorter step and bend less.' },
  'Split squat': { s: 'Stand with one foot a big step in front of the other, feet hip-width apart for balance. Hold something steady if you need to.', m: ['Lower your back knee towards the floor.', 'Stop when it feels like enough. Front knee stays over your foot.', 'Push through your front foot to come back up. Swap legs halfway.'], f: 'Thigh and bottom of the front leg', e: 'Hold a chair, go less deep, or put the weights down.' },
  'Kettlebell step-up': { s: 'Stand facing a sturdy step. Hold the kettlebell against your chest.', m: ['Place your whole foot on the step.', 'Push through that foot and stand up onto the step.', 'Step back down slowly. Do all your reps, then swap legs.'], f: 'Thigh and bottom of the stepping leg', e: 'Put the bell down and hold a rail.' },
  'Banded side step': { s: 'Put a loop band round your legs just above your knees. Stand with knees soft.', m: ['Step one foot out to the side against the band.', 'Bring the other foot in, keeping some tension.', 'Take your steps one way, then come back.'], f: 'The outside of your hips', e: 'Use a lighter band, or take smaller steps.' },
  'Glute bridge march': { s: 'Lie on your back, knees bent, feet flat. Lift your hips into a bridge.', m: ['Keep your hips level.', 'Lift one foot an inch off the floor.', 'Put it down and lift the other. Keep going.'], f: 'Bottom and the backs of your thighs', e: 'Keep both feet down and just hold the bridge.' },

  /* press */
  'Bag press overhead': { s: 'Sit or stand tall. Hold a filled bag or a water bottle in each hand at your shoulders.', m: ['Tuck your ribs down, do not lean back.', 'Press your hands straight up until your arms are nearly straight.', 'Lower slowly to your shoulders.'], f: 'Shoulders', e: 'Do it seated with your back supported, or use less weight.' },
  'Overhead press': { s: 'Sit or stand tall. Hold a dumbbell in each hand at your shoulders, palms forward.', m: ['Tuck your ribs down, do not lean back.', 'Press the weights straight up until your arms are nearly straight.', 'Lower slowly to your shoulders.'], f: 'Shoulders', e: 'Do it seated with your back supported, or use lighter weights.' },
  'Kettlebell press': { s: 'Stand tall. Hold the kettlebell in one hand at your shoulder, the bell resting on the back of your forearm.', m: ['Squeeze your bottom and tuck your ribs down.', 'Press the bell straight up.', 'Lower slowly. Do all your reps, then swap arms.'], f: 'Shoulder', e: 'Use both hands on the bell, or a lighter one.' },
  'Band overhead press': { s: 'Stand on the middle of the band. Hold an end in each hand at your shoulders.', m: ['Tuck your ribs down.', 'Press your hands straight up.', 'Lower slowly.'], f: 'Shoulders', e: 'Stand on the band with one foot, not two.' },
  'Shoulder press machine': { s: 'Adjust the seat so the handles are level with your shoulders. Back against the pad.', m: ['Grip the handles.', 'Press up until your arms are nearly straight. Do not shrug.', 'Lower slowly.'], f: 'Shoulders', e: 'Take weight off.' },
  'Wall slide': { s: 'Stand with your back, head and bottom against a wall. Arms up in a goalpost shape, backs of your hands near the wall.', m: ['Slide your arms up the wall.', 'Go only as far as is comfortable.', 'Slide back down slowly.'], f: 'Shoulders and upper back', e: 'Step your feet further from the wall.' },

  /* carry */
  'Suitcase hold': { s: 'Stand tall beside something steady. Hold a heavy bag in one hand, like a suitcase.', m: ['Stand as if the bag were not there. Do not lean.', 'Hold for the time.', 'Put it down and swap hands.'], f: 'The side of your waist, your grip and your shoulder', e: 'Use a lighter bag.' },
  'Suitcase hold by a worktop': { s: 'Stand beside a worktop with one hand resting on it. Hold a weight in the other hand, like a suitcase.', m: ['Stand tall. Do not lean towards the weight.', 'Hold for the time.', 'Put it down, turn round and swap hands.'], f: 'The side of your waist and your grip', e: 'Use a lighter weight.' },
  'Suitcase carry': { s: 'Stand tall. Hold one heavy dumbbell in one hand, like a suitcase.', m: ['Walk slowly in a straight line. Do not lean.', 'Keep walking for the time, turning when you need to.', 'Put it down and swap hands.'], f: 'The side of your waist, your grip and your shoulder', e: 'Use a lighter weight, or stand still and hold it.' },
  'Kettlebell carry': { s: 'Stand tall. Hold the kettlebell in one hand, like a suitcase.', m: ['Walk slowly in a straight line. Do not lean.', 'Keep walking for the time, turning when you need to.', 'Put it down and swap hands.'], f: 'The side of your waist, your grip and your shoulder', e: 'Use a lighter bell, or stand still and hold it.' },
  'Band pull-apart': { s: 'Stand tall. Hold the band in both hands in front of your chest, arms straight, hands shoulder-width apart.', m: ['Pull your hands apart until the band touches your chest.', 'Squeeze your shoulder blades together.', 'Return slowly.'], f: 'Between your shoulder blades and the backs of your shoulders', e: 'Hold the band wider so it is slacker.' }
};
if (typeof module !== 'undefined') module.exports = GUIDES;
